# Generated by Django 5.2.8 on 2025-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=200, verbose_name='Artiste')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('duree', models.IntegerField(verbose_name='Durée (secondes)')),
                ('style', models.CharField(max_length=100, verbose_name='Style')),
            ],
            options={
                'verbose_name': 'Musique',
                'verbose_name_plural': 'Musiques',
            },
        ),
    ]
