# Generated by Django 5.2.8 on 2025-12-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musique',
            name='duree',
        ),
    ]
